baseurl = "/"
languageCode = "zh-CN"
title = "北美华人基因组学在线沙龙"
theme = "hugo-xmag"
disqusShortname = ""
googleAnalytics = ""
paginate = 6
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishDir = "docs"

[blackfriday]
  extensionsmask = ["noIntraEmphasis"]

[permalinks]
  post = "/:year/:month/:slug/"


[[menu.top]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.top]]
  name = "预告"
  url = "/coming/"
  weight = 3

[[menu.top]]
  name = "征集志愿者"
  url = "/contribute/"
  weight = 4

[[menu.top]]
  name = "注册"
  url = "/subscribe/"
  weight = 4

[params.banner]
  src = "/img/logo.png"
  alt = "CGM标志"

[[params.banner.source]]
  media = "(min-width: 715px)"
  srcset = "/img/logo-wide.png"

[[params.banner.source]]
  media = "(max-width: 380px)"
  srcset = "/img/logo-80.png"

[params.text]
  about_author = "关于作者"
  author_delimiter = " / "
  back = "&larr; 返回首页"
  edit = "编辑本页 &rarr;"
  tags = "关键词："
  comment = "发表/查看评论"
  truncated = "&hellip;&hellip;"
  uncategorized = "未分类"
  title_categories = "栏目分类"
  title_tags = "关键词列表"

[params]
	copyright = "北美华人基因组学在线沙龙 2017"
	description = "基因组学在线讨论平台"

  summary_length = 100
  github_edit = "https://github.com/cgmonline/cgmonline/edit/master/content/"

  footer = "&copy; 北美华人基因组学在线沙龙 2017 | [Github](https://github.com/cgmonline) | [YouTuBe](https://www.youtube.com/channel/UCk4tsPZOzGkP2IaU4YvUG_g)"
