baseurl = "https://cgmonline.co/"
languageCode = "zh-CN"
title = "华人基因组学在线沙龙"
theme = "hugo-xmag"
disqusShortname = "cgmonline-co"
googleAnalytics = "UA-48206713-4"
paginate = 10
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishDir = "docs"

[blackfriday]
  extensionsmask = ["noIntraEmphasis"]

# prevent hugo from creating folders/indexes for each section
disableKinds = ["section"]

# adding taxonomy term 'archive'
[taxonomies]
  archive = "archive"
  tag = "tags"
  category = "categories"

# Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
# they have to be referred from static root. Example
[[params.customCSS]]
  href = "css/custom.css"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.top]]
  name = "首页"
  url = "/"
  weight = 1


[[menu.top]]
  name = "往期活动"
  url = "/tags/talks/"
  weight = 5


[[menu.main]]
  name = "关键词"
  url = "/tags/"
  weight = 5

[[menu.main]]
  name = "人物专访"
  url = "/categories/人物专访/"
  weight = 1

[[menu.main]]
  name = "专题讨论"
  url = "/categories/专题讨论/"
  weight = 2

[[menu.main]]
  name = "学术报告"
  url = "/categories/学术报告/"
  weight = 3


[[menu.main]]
  name = "企业群"
  url = "/categories/企业群/"
  weight = 6

[params.banner]
  src = "/img/logo.png"
  alt = "CGM标志"

[[params.banner.source]]
  media = "(min-width: 715px)"
  srcset = "/img/new-logo-wide2020.png"

[[params.banner.source]]
  media = "(max-width: 380px)"
  srcset = "/img/new-logo-wide2020.png"

[params.text]
  about_author = "关于作者"
  author_delimiter = " / "
  back = "&larr; 返回首页"
  edit = "编辑本页 &rarr;"
  tags = "关键词："
  comment = "发表/查看评论"
  truncated = "&hellip;&hellip;"
  uncategorized = "未分类"
  title_categories = "栏目分类"
  title_tags = "关键词列表"

[params]
	copyright = "华人基因组学在线沙龙 2020"
	description = "基因组学在线讨论平台"

  summary_length = 200
  github_edit = "https://github.com/cgmonline/cgmonline/edit/master/content/"

  footer = "&copy; 华人基因组学在线沙龙 2021 | [Github](https://github.com/cgmonline) | [YouTube](https://www.youtube.com/channel/UCk4tsPZOzGkP2IaU4YvUG_g)"
